server:
  port: 8080

spring:
  application:
    name: rotido-backend

  data:
    mongodb:
      uri: mongodb://localhost:27017/rotido
      database: rotido

#  datasource:
#    url: jdbc:mysql://localhost:3306/rotido
#    driver-class-name: org.h2.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#  task:
#    scheduling:
#      enabled: true

#logging:
#  level:
#    org.springframework: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
#    com.rotido.backend: DEBUG
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: your-very-secure-and-long-secret-key-of-at-least-32-bytes-for-jwt-signing

app:
  encryption:
    key: MyCompanySecretKey2024!

MQTT:
  URL: tcp://server.thinkfinitylabs.com:1883
  CLIENT_ID: rotido-listener
  TOPIC: Rotido/notify/#
  USERNAME: ""
  PASSWORD: ""
